"""
Automated Ur/Web Translator
Reads app_spec.json and generates main.ur, main.urs, and db.sql
"""

import json
import os
import sys


def load_spec(path="app_spec.json"):
    """Load and return the application specification from JSON."""
    with open(path, "r") as f:
        return json.load(f)


def generate_db_sql(spec):
    """Generate the database schema SQL file."""
    table = spec["table"]
    seq   = spec["sequence"]
    app   = spec["app_name"].lower()

    lines = []
    lines.append("-- Auto-generated by urweb-translator")
    lines.append("-- Database schema for: {}\n".format(spec["page_title"]))
    lines.append("CREATE TABLE uw_{} (".format(table["name"]))
    lines.append("    uw_Id INT PRIMARY KEY,")

    for i, field in enumerate(table["fields"]):
        comma = "," if i < len(table["fields"]) - 1 else ""
        lines.append("    uw_{} TEXT NOT NULL{}".format(field["name"], comma))

    lines.append(");\n")
    lines.append("CREATE SEQUENCE uw_{};".format(seq))

    return "\n".join(lines)


def generate_main_urs(spec):
    """Generate the module signature file."""
    lines = []
    lines.append("(* Auto-generated by urweb-translator *)")
    lines.append("val main : unit -> transaction page")
    return "\n".join(lines)


def generate_main_ur(spec):
    """Generate the main application logic file."""
    table   = spec["table"]
    seq     = spec["sequence"]
    title   = spec["page_title"]
    feats   = spec["features"]
    tname   = table["name"]
    fields  = table["fields"]

    # Build field list string e.g. "Id : int, Username : string, Content : string"
    field_decls = "Id : int, " + ", ".join(
        "{} : string".format(f["name"]) for f in fields
    )

    # Build INSERT columns and VALUES
    insert_cols = "Id, " + ", ".join(f["name"] for f in fields)
    insert_vals = "{[id]}, " + ", ".join("{[" + f["name"].lower() + "]}" for f in fields)

    # Build validation block
    field_params = " ".join(
        "({} : string)".format(f["name"].lower()) for f in fields
    )

    validation_lines = []
    for f in fields:
        fname = f["name"].lower()
        validation_lines.append(
            '    if {} = "" then\n'
            '        error <xml>{} must not be empty.</xml>'.format(fname, f["name"])
        )
        if feats.get("input_validation") and "max_length" in f:
            validation_lines.append(
            '    else if strlen {} > {} then\n'
            '        error <xml>{} must be {} characters or fewer.</xml>'.format(
                fname, f["max_length"], f["name"], f["max_length"]
            ))

    validation_block = "\n    else\n".join(validation_lines)

    # Build insert statement
    insert_stmt = (
        "        id <- nextval {};\n"
        "        dml (INSERT INTO {} ({}) VALUES ({}));\n"
        "        return ()"
    ).format(seq, tname, insert_cols, insert_vals)

    # Build query display
    order_clause = " ORDER BY {}.Id DESC".format(tname.capitalize()) if feats.get("order_by_desc") else ""
    field_display = " ".join(
        '<b>{{[r.{cap}.{f}]}}</b>: {{[r.{cap}.{f2}]}} '.format(
            cap=tname.capitalize(), f=fields[0]["name"], f2=fields[1]["name"]
        ) if i == 0 else ""
        for i, _ in enumerate(fields)
    )

    query_block = (
        "    rows <- queryX (SELECT * FROM {tname}{order})\n"
        "        (fn r =>\n"
        "            <xml>\n"
        "                <li>\n"
        "                    <b>{{[r.{cap}.{f0}]}}</b>: {{[r.{cap}.{f1}]}}\n"
        "                </li>\n"
        "            </xml>);\n"
        "    return <xml><ul>{{rows}}</ul></xml>"
    ).format(
        tname=tname,
        order=order_clause,
        cap=tname.capitalize(),
        f0=fields[0]["name"],
        f1=fields[1]["name"]
    )

    # Build textbox inputs
    input_fields = "\n                ".join(
        '<textbox{{#{fname}}} placeholder="{flabel} (max {maxlen} chars)"/>'.format(
            fname=f["name"].lower(),
            flabel=f["name"],
            maxlen=f.get("max_length", 100)
        )
        for f in fields
    )

    # Build rpc call
    rpc_gets = "\n                        ".join(
        "{fl} <- get {fl};".format(fl=f["name"].lower()) for f in fields
    )
    rpc_args = " ".join(f["name"].lower() for f in fields)

    # Reactive or static refresh
    if feats.get("reactive_refresh"):
        main_body = (
            "fun main () : transaction page =\n"
            "    msgs <- source <xml/>;\n"
            "    let\n"
            "        fun refresh () =\n"
            "            m <- rpc (listMessages ());\n"
            "            set msgs m\n"
            "    in\n"
            "        return <xml>\n"
            "            <head>\n"
            "                <title>{title}</title>\n"
            "                <style>\n"
            "                    body {{{{ font-family: sans-serif; max-width: 700px;\n"
            "                            margin: 40px auto; padding: 0 20px; }}}}\n"
            "                    input, textarea {{{{ width: 100%; margin-bottom: 10px;\n"
            "                                       padding: 8px; box-sizing: border-box; }}}}\n"
            "                    button {{{{ padding: 10px 20px; background: #2c7be5;\n"
            "                              color: white; border: none; cursor: pointer; }}}}\n"
            "                </style>\n"
            "            </head>\n"
            "            <body onload={{refresh ()}}>\n"
            "                <h1>{title}</h1>\n"
            "                <p>Post a message below. All input is handled securely by Ur/Web.</p>\n"
            "                <h2>Post a Message</h2>\n"
            "                {inputs}\n"
            "                <button value=\"Post Message\"\n"
            "                    onclick={{fn _ =>\n"
            "                        {gets}\n"
            "                        rpc (addMessage {args});\n"
            "                        refresh ()\n"
            "                    }}/>\n"
            "                <h2>All Messages</h2>\n"
            "                <dyn signal={{signal msgs}}/>\n"
            "            </body>\n"
            "        </xml>\n"
            "    end"
        ).format(
            title=title,
            inputs=input_fields,
            gets=rpc_gets,
            args=rpc_args
        )
    else:
        main_body = "(* reactive_refresh disabled: static page only *)"

    # Assemble full file
    lines = []
    lines.append("(* Auto-generated by urweb-translator *)")
    lines.append("(* Source application: {} *)\n".format(title))
    lines.append("table {} : {{ {} }}".format(tname, field_decls))
    lines.append("  PRIMARY KEY Id\n")
    lines.append("sequence {}\n".format(seq))
    lines.append("(* Server-side: add a validated message *)")
    lines.append("fun addMessage {} : transaction unit =".format(field_params))
    lines.append(validation_block)
    lines.append("    else\n" + insert_stmt + "\n")
    lines.append("(* Server-side: fetch all messages as XML *)")
    lines.append("fun listMessages () : transaction xbody =")
    lines.append(query_block + "\n")
    lines.append("(* Main page *)")
    lines.append(main_body)

    return "\n".join(lines)


def write_file(filename, content, output_dir="output"):
    """Write generated content to a file in the output directory."""
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, filename)
    with open(path, "w") as f:
        f.write(content)
    print("  Generated: {}".format(path))


def main():
    spec_path = sys.argv[1] if len(sys.argv) > 1 else "app_spec.json"

    print("Ur/Web Automated Translator")
    print("============================")
    print("Reading spec from: {}\n".format(spec_path))

    spec = load_spec(spec_path)

    print("Generating files for: {}".format(spec["page_title"]))

    write_file("db.sql",   generate_db_sql(spec))
    write_file("main.urs", generate_main_urs(spec))
    write_file("main.ur",  generate_main_ur(spec))

    print("\nDone. Files written to ./output/")
    print("To build: copy output files to your Ur/Web project and run: urweb main")


if __name__ == "__main__":
    main()
