-- Auto-generated by urweb-translator
-- Database schema for: Secure Message Board

CREATE TABLE uw_messages (
    uw_Id INT PRIMARY KEY,
    uw_Username TEXT NOT NULL,
    uw_Content TEXT NOT NULL
);

CREATE SEQUENCE uw_msgSeq;
